version: '2.0'
services:
  github:
    image: eduwass/docker-git-webhook
    volumes:
      - ./custom_scripts:/custom_scripts
      - .:/code
    expose:
      - 8555
    environment:
      GIT_HOOK_TOKEN:
      AFTER_PULL_COMMANDS: git submodule update --init
      GIT_REPO: git@github.com:lyuzashi/mqtt-smarthome-system.git
  bus:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    network_mode: host
    expose:
      - 1883
  interfaces:
    image: keymetrics/pm2:latest-alpine
    working_dir: /home/node/app
    volumes:
      - ./interfaces:/home/node/app
      # ./data/interfaces/hue:/home/<username>/.hue2mqtt
    command: /bin/ash -c 'yarn install; pm2-runtime start main.config.js'
    tmpfs: /home/node/app/node_modules/
    network_mode: host
  advertise:
    image: flungo/avahi
    volumes:
      - ./services:/etc/avahi/services
    network_mode: host
    expose:
      - 5353
    environment:
      SERVER_ENABLE_DBUS: 'no'
      WIDE_AREA_ENABLE_WIDE_AREA: 'yes'
      SERVER_HOST_NAME: HAL9000
