version: "3"
services:
  bus:
    image: eclipse-mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    expose:
      - 1883
    networks:
      - bus
  interfaces:
    image: keymetrics/pm2:latest-alpine
    working_dir: /home/node/app
    volumes:
      - ./interfaces:/home/node/app
    command: /bin/ash -c 'yarn install; pm2-runtime start main.config.js'
    tmpfs: /home/node/app/node_modules/
    networks:
      - bus
      - interfaces

networks:
  bus:
  interfaces:
  logic:
  visualizations:

