import './system/mqtt';
import './system/git';
import './system/influx';
import './logic';
import './interfaces/midi';
import './interfaces/hap';
import './interfaces/hue';
import './interfaces/gpio';
import './interfaces/location';
// import './interfaces/micro';
import './interfaces/lights';
import './visualizations/web';