MotionDetected:
  type: boolean
  methods: [status, get]
  logic:
    - name: raw
OccupancyDetected:
  type: boolean
  methods: [status, get]
  logic: 
    - name: raw
    - name: timeout
      delay: 1800000
ContinuousMotion:
  type: boolean
  methods: [status, get]
  logic: 
    - name: raw
    - name: retrigger
      delay: 5000
On:
  type: boolean
  methods: [status, get, set]
Brightness:
  type: float
  methods: [status, get, set]
Longitude:
  type: float
  methods: [status, get]
Latitude:
  type: float
  methods: [status, get]
Online:
  type: boolean
  methods: [status, get]
  default: false
