- 
  hub: neptr pigpio
  id: 4
  type: motion sensor
  protocol:
    - type: pigpio
  interface:
    - type: gpio
      mode: in
  name: Motion Sensor
  room: Bedroom
  location: [4500, 2000]
  # topic: motion/status/bedroom
  # request: motion/get/bedroom
-
  topic: motion/status/dining
  request: motion/get/dining
  id: 7
  direction: in
-
  id: WORLDE easy control
  type: controller
  protocol:
    - type: usb
  interface:
    - type: midi
      definition: WORLDE easy control
  participant: controller
  methods: [status, get] # Get will only return cached values for checking bank/modifiers in logic
- 
  id: Control Desk Display
  type: display
  interface:
    - type: web
      definition: WORLDE easy control
  participant: display
  methods: [set]