desk-left:
  name: Desk Left
  manufactuer: OSRAM
  model: 1
  serial: 1
  identify: lights/set/Desk Left/alert
  services:
    - service: Lightbulb
      characteristics:
        On:
          set:
            topic: lights/set/Desk Left/on
          get:
            topic: lights/status/Desk Left/on
            request: lights/get/Desk Left/on
            map:
              true: true
              false: false
        Brightness:
          set:
            topic: lights/set/Desk Left/brightness
            map:
              0-100: 0-255
          get:
            topic: lights/status/Desk Left/brightness
            request: lights/get/Desk Left/brightness
            map:
              0-255: 0-100
        ColorTemperature:
          set:
            topic: lights/set/Desk Left/colorTemp
          get:
            topic: lights/status/Desk Left/colorTemp
            request: lights/get/Desk Left/colorTemp
desk-right:
  name: Desk Right
  manufactuer: OSRAM
  model: 1
  serial: 1
  identify: lights/set/Desk right/alert
  services:
    - service: Lightbulb
      characteristics:
        On:
          set:
            topic: lights/set/Desk right/on
          get:
            topic: lights/status/Desk right/on
            request: lights/get/Desk right/on
            map:
              true: true
              false: false
        Brightness:
          set:
            topic: lights/set/Desk right/brightness
            map:
              0-100: 0-255
          get:
            topic: lights/status/Desk right/brightness
            request: lights/get/Desk right/brightness
            map:
              0-255: 0-100
        ColorTemperature:
          set:
            topic: lights/set/Desk right/colorTemp
          get:
            topic: lights/status/Desk right/colorTemp
            request: lights/get/Desk right/colorTemp
kitchen-accent:
  name: Kitchen accent light
  manufactuer: IKEA of Sweden
  model: TRADFRI bulb E14 W
  serial: 1
  identify: lights/set/Kitchen accent light/alert
  colorTemperature: 2700 K # 370 mired
  services:
    - service: Lightbulb
      characteristics:
        On:
          set:
            topic: lights/set/Kitchen accent light/on
          get:
            topic: lights/status/Kitchen accent light/on
            request: lights/get/Kitchen accent light/on
            map:
              true: true
              false: false
        Brightness:
          set:
            topic: lights/set/Kitchen accent light/brightness
            map:
              0-100: 0-255
          get:
            topic: lights/status/Kitchen accent light/brightness
            request: lights/get/Kitchen accent light/brightness
            map:
              0-255: 0-100
dining-motion:
  name: Dining Motion Sensor
  manufactuer: RobotJamie
  model: 1
  serial: 1
  services:
    - service: MotionSensor
      characteristics:
        MotionDetected:
          get:
            topic: motion/status/dining
            request: motion/get/dining
            map:
              true: true
              false: false
garden-lights:
  name: Garden Lights
  manufactuer: RobotJamie
  model: 1
  serial: 1
  identify: relays/set/GardenLights/led
  services:
    - service: Outlet
      characteristics:
        On:
          set:
            topic: relays/set/GardenLights/on
            map:
              true: 1 
              false: 0
          get:
            topic: relays/status/GardenLights/on
            request: relays/get/GardenLights/on
            map:
              1: true
              0: false
lounge-lanterns:
  name: Lounge Lanterns
  manufactuer: RobotJamie
  model: 1
  serial: 1
  identify: lights/set/Lanterns/led
  services:
    - service: Lightbulb
      characteristics:
        On:
          set:
            topic: lights/set/Lanterns 1/on
            map:
              true: 1 
              false: 0
          get:
            topic: lights/status/Lanterns 1/on
            request: lights/get/Lanterns 1/on
            map:
              1: true
              0: false
        Brightness:
          set:
            topic: lights/set/Lanterns 1/brightness
            map:
              0-100: 0-1023
          get:
            topic: lights/status/Lanterns 1/brightness
            request: lights/get/Lanterns 1/brightness
            map:
              0-1023: 0-100