banks:
  - message: 123 456 0 1
    name: Lighting
    notes:
      - name: Slider 1
        message: 5
        map:
          from: [0, 125]
          to: [0, 512]
        topic: hue/lounge lamp/brightness
        modifier:
          name: Button 1
          value: 125
      - name: Button 1
        message: 3