motion sensor:
  hap: true
  participant: motion
  component: motion-sensor
  service: MotionSensor
  characteristics:
    - name: MotionDetected
    - name: OccupancyDetected
    - name: ContinuousMotion